### ISSUE TITLE
parameter estimation in snowIRT

### ISSUE THREAD

**Issue by jlpina188** [hyunsooseol/snowIRT#14]
I am using the snowIRT and snowRMM modules for my classes where I explain the Rasch model. The snowRMM module estimates item parameters appropriately so that the mean of the difficulty parameters is 0. However, this is not the case in the snowIRT module. What is the reason?

**Comment by hyunsooseol** [comment]
Hi [jlpina188](https://github.com/jlpina188)

The difference in the treatment of item difficulty parameter centering between the snowIRT and snowRMM modules arises from the estimation methods they use. The snowIRT module employs Marginal Maximum Likelihood (MML) estimation, which is implemented using the TAM R package[1](https://forum.jamovi.org/viewtopic.php?t=1938)[2](https://rdrr.io/github/hyunsooseol/snowIRT/src/R/polytomous.b.R). This method does not inherently center the mean of the item difficulty parameters at zero. MML estimation focuses on estimating item parameters by integrating over person abilities, which often results in item difficulty parameters that are not centered around zero unless explicitly adjusted.
On the other hand, the snowRMM module likely uses a different estimation method that includes a constraint to ensure that the mean of item difficulty parameters is zero. This is a common practice in Rasch model implementations to facilitate interpretation and comparison of item difficulties.
The lack of automatic centering in snowIRT is due to the nature of MML estimation, which does not impose this constraint by default. If centering is desired in analyses using snowIRT, additional steps must be taken to adjust the item difficulty parameters post-estimation.

For more information, click the following link in instruction.
![image](https://github.com/user-attachments/assets/4471dc0e-790b-47be-800d-70c2ac458fee)

Kind Regards
Seol

**Comment by jlpina188** [comment]
Thank you very much for the quick response. I'll use the snowRMM module to explain the basics of the Rasch model. Then I'll switch to the snowIRT module.
